# Generated by Django 6.1 on 2026-08-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_id_alter_riderprofile_id'),
        ('delivery', '0001_initial'),
        ('orders', '0005_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytracking',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliverytracking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='deliverytracking',
            name='longitude',
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.riderprofile'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
