# Generated by Django 5.2.6 on 2026-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customusermodel_bio_customusermodel_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(default='Home', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Punjab', max_length=100),
            preserve_default=False,
        ),
    ]
