# Generated by Django 5.2.6 on 2026-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
